### ISSUE TITLE
Use JSON-LD

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/licenses#1]
## Problem

Many tools will need licenses lists. Let's show them immediately how it's done properly by using Linked Data standards
## Solution:

Do something like this?

``` json
{
  "@context" : {
    "title" : "http://purl.org/dc/terms/title",
    "identifier" : "http://purl.org/dc/terms/identifier",
    "seeAlso" : "http://www.w3.org/2000/01/rdf-schema#seeAlso",
    "comment" : "http://www.w3.org/2000/01/rdf-schema#comment",
    "cc" : "http://creativecommons.org/ns#",
    "permits" : { "@id":"http://creativecommons.org/ns#permits", "@type" : "@id" },
    "requires" : { "@id":"http://creativecommons.org/ns#requires", "@type" : "@id" }
  },
  "@graph" : [ {
      "@id" : "http://creativecommons.org/publicdomain/zero/1.0/",
      "@type" : [ "http://creativecommons.org/ns#License","http://purl.org/dc/terms/LicenseDocument"],
      "title": "CC0 1.0 Universal",
      "identifier" : "CC0 1.0",
      "permits" : ["cc:Reproduction","cc:DerivativeWorks","cc:Distribution"],
      "opendefinition" : "true",
      "seeAlso" : "http://www.opendefinition.org/licenses/cc-zero",
      "otherinfo" : "other info you might need"
    }, {
      "comment" : "An unknown open license with attribution",
      "permits" : ["cc:Reproduction","cc:DerivativeWorks","cc:Distribution"],
      "requires" : [ "cc:Attribution", "cc:Notice" ]
    },{
      "comment" : "An unknown open license with attribution and share-alike",
      "permits" : ["cc:Reproduction","cc:DerivativeWorks","cc:Distribution"],
      "requires" : [ "cc:Attribution", "cc:Notice", "cc:ShareAlike" ]
    },
    ...
  ]
}
```

**Comment by pietercolpaert** [comment]
Because I thought you were going to have issues with licenses without a certain URI, I've added 2 examples of how to deal with these. This is the JSON-LD equivalent of a blank-node :)

**Comment by coreation** [comment]
Agreed, current keywords of certain lists of licenses sometimes make no sense. Let's move to LOD.

**Comment by coreation** [comment]
@pietercolpaert any idea on what ns "Maintainer" could have? Maintainer being http://creativecommons.org for example for certain licenses.

**Comment by pietercolpaert** [comment]
the predicate `maintainer` could be  `dct:publisher`?

**Comment by coreation** [comment]
I think that could be used for it. 
Just to check, busy on the okfn licenses: share, create, adapt are respectively cc:reproduction, cc:distribution, cc:derivativeworks.

Why not cc:Sharing (prohibits the re-use for commercial applications) -> sharing sets a constraint, in the case for [this](http://opendatacommons.org/licenses/pddl/summary/) sharing has no implications on commercial use.

**Comment by pietercolpaert** [comment]
### Why I didn't mention cc:Sharing

If you add "/rdf" to a creative commons license document url, then you get the rdf version (you can also take the RDFa from the page): https://creativecommons.org/licenses/by/4.0/rdf. I didn't see cc:Sharing in any of the documents for licenses usable for open data. I may be wrong though.

### Why not cc:Sharing

No idea why it isn't applied. To be honest: I don't fully understand the semantics behind its explanation:

```
 permits commercial derivatives, but only non-commercial distribution
```

any idea what that could mean?

**Comment by coreation** [comment]
I think commercial derivates are like "smart maps", commercial distribution would be commercial distribution of the data behind the maps, which were/are open data (?)

**Comment by pietercolpaert** [comment]
not sure, in each case, I would try to stick to what can be found in the RDF of the cc licenses

**Comment by coreation** [comment]
Doing just that ;)

**Comment by coreation** [comment]
Still need some additional flemish gov licenses in order to close this issue.
